#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' # Allow over firewall
echo "Hello World!" | sudo tee /var/www/html/index.html

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

if ! grep -q "location /redirect_me" "/etc/nginx/sites-available/default"; then
        ADD_REDIRECT301="\\\tlocation /redirect_me {\n\t\treturn 301 https://google.com;\n\t}\n"
        sudo sed -i "48i $ADD_REDIRECT301" /etc/nginx/sites-available/default #add at line 48
fi

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

if ! grep -q "error_page 404 /error_404." "/etc/nginx/sites-available/default"; then
        sudo sed -i '57i\       error_page 404 /error_404.html;' /etc/nginx/sites-available/default
fi
sudo service nginx start
