#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' # Allow over firewall
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# add a redirection
if ! grep -q "location /redirect_me" "/etc/nginx/sites-available/default"; then
        ADD_REDIRECT301="\\\tlocation /redirect_me {\n\t\treturn 301 https://google.com;\n\t}\n"
        sudo sed -i "48i $ADD_REDIRECT301" /etc/nginx/sites-available/default #add at line 48
fi

# Create a custom 404error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
if ! grep -q "error_page 404 /error_404." "/etc/nginx/sites-available/default"; then
        sudo sed -i '57i\       error_page 404 /error_404.html;' /etc/nginx/sites-available/default
fi

# shellcheck disable=SC2154

# Add custom header
if ! grep -q "add_header X-Served-By" "/etc/nginx/sites-available/default"; then
        ADD_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"
        sudo sed -i "24i $ADD_HEADER" /etc/nginx/sites-available/default
fi

sudo service nginx restart
