#!/usr/bin/env bash
# configure Nginx to be running, and listening on port 80 of all the server’s active IPv4 IPs

# check if nginx is running
if ! pgrep nginx >/dev/null; then
	sudo service nginx start
fi

# Check if Nginx is listening on port 80
if ! sudo netstat -tuln | grep -q ':80 '
then
	if [[ -f "/etc/nginx/nginx.conf" ]]; then
        # Backup existing configuration file
        sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

        # Add or modify the necessary configuration to listen on port 80
        sudo sed -i 's/\(listen\s*[^;]*\)80/\180/g' /etc/nginx/nginx.conf

        # Restart Nginx to apply changes
        sudo service nginx restart
	fi
fi
