#!/usr/bin/env bash
# configure Nginx to be running, and listening on port 80 of all the server’s active IPv4 IPs
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sudo sed -i 's/\(listen\s*[^;]*\)80/\180/g' /etc/nginx/nginx.conf
sudo service nginx restart
