#!/usr/bin/env bash
# a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid

counter=0
while [ $counter -eq 0 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
done

handle_sigquit_sigterm() {
	rm /var/run/myscript.pid
}

trap 'handle_sigquit_sigterm' SIGQUIT
trap 'handle_sigquit_sigterm' SIGTERM
