#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS

FILE="/etc/passwd"
delimiter=":"
while IFS=$delimiter read -r user passwd uid gid uinfo homedir shell
do
	echo "The user $user is part of the $gid gang, lives in $homedir and \
rides $shell. $uid's place is protected by the passcode $passwd, \
more info about the user here: $uinfo"
done < "$FILE"
