#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration,
#+ displays Best School and then Hi on a new line.

counter=1
while [ $counter -le 11 ]
do
	if [ $counter -eq 10 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	
	((counter++))
done
