#!/usr/bin/env bash
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash
#+ is displayed (refer to the example)

fileList=$(ls)
for file in $fileList;
do
	# Check if the file is not hidden and is a regular file
    	if [[ ! $file =~ ^\..* && -f $file ]];
	then
		echo "$file" | cut -d'-' -f2-
	fi
done
