#!/usr/bin/env bash

# The content of the current directory
# In a list format
# Where only the part of the name after the first dash
#+ is displayed (refer to the example)

dirList="./glob *"
for i in $dirList;
do
	echo "$i" | awk -F- '{print $2}'
done
