#!/usr/bin/env bash
# create an nginx user to run your nginx webservers, nginx listens on all active IPs on port 8080
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
