#!/usr/bin/env bash
#  creates an RSA key pair.
# Name of created private key - school
# Number of bits in the created key to be created 4096
# The created key is protected by the passphrase betty

ssh-keygen -t rsa -b 4096 -f school -N "betty"
